---
image: qbittorrent
version: v0.2.0
name: qBittorrent
description: "The [Qbittorrent](https://www.qbittorrent.org/) project aims to provide an open-source software alternative to µTorrent. qBittorrent is based on the Qt toolkit and libtorrent-rasterbar library."
ext_release: v2.5.0
arch:
  - aarch64
  - x86_64
