---
image: docker-mod-vuetorrent
version: v0.4.14
name: docker-mod-vuetorrent
description: "The [Qbittorrent](https://www.qbittorrent.org/) project aims to provide an open-source software alternative to µTorrent. qBittorrent is based on the Qt toolkit and libtorrent-rasterbar library."
ext_release: "v2.30.0"
arch:
  - all
